{% set name = "clouddrift" %}
{% set version = "0.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clouddrift-{{ version }}.tar.gz
  sha256: db97b4b46577a310e35dd0552c8294efa908bca34166bcb458b3d20d258a74c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python>=3.9
    - numpy>=1.21.6
    - xarray>=2023.5.0
    - pandas>=1.3.4
    - netcdf4>=1.6.4
    - pyarrow>=9.0.0
    - tqdm>=4.64.1
    - fsspec>=2022.8.2
    - llvmlite>=0.38.1
    - awkward>=2.0.0
    - pip>=22.2.2
    - aiohttp>=3.8.4
    - requests>=2.31.0
    - zarr>=2.14.2

test:
  imports:
    - clouddrift
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/clouddrift/
  summary: Accelerating the use of Lagrangian data for atmospheric, oceanic, and climate sciences
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - philippemiron
    - selipot
