{% set name = "clouddrift" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clouddrift-{{ version }}.tar.gz
  sha256: 6b6cae61a910288f5871710e17d77f444dd0d3d96ca90623a80c8ca6b9d22977

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - aiohttp >=3.8.4
    - awkward >=2.0.0
    - fsspec >=2022.3.0
    - netcdf4 >=1.6.4
    - numpy >=1.22.4
    - pyarrow >=8.0.0
    - tqdm >=4.64.0
    - requests >=2.31.0
    - xarray >=2023.5.0
    - zarr >=2.14.2

test:
  imports:
    - clouddrift
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Accelerating the use of Lagrangian data for atmospheric, oceanic, and climate sciences
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - philippemiron
